
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
author:
  name: Andrey Kuprianov
  email: "andrey@kuprum.xyz"
title: Systems Made Simple
description: Enhancing software development practices for better security and reliability. Subject to the Creative Commons Attribution 4.0 International License.
show_downloads: false
github.is_project_page: false
domain: systems-made-simple.dev
url: https://systems-made-simple.dev
baseurl: /
twitter_username: kuprumion
github_username:  andrey-kuprianov
plugins:
  - jekyll-feed
  - jemoji
exclude:
  - _scripts
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/